Class {
	#name : #JbReturnStatementNode,
	#superclass : #Object,
	#instVars : [
		'expression'
	],
	#category : #'Jauburn-AST-Core'
}

{ #category : #'as yet unclassified' }
JbReturnStatementNode >> executeIn: anEnvironment [
	| sig | 
	sig := JbReturnValueException new.
	sig returnValue: (self expression evaluateIn: anEnvironment).
	sig signal
	
]

{ #category : #accessing }
JbReturnStatementNode >> expression [
	^ expression
]

{ #category : #accessing }
JbReturnStatementNode >> expression: anObject [
	expression := anObject
]
